# Generated by Django 5.2.8 on 2025-11-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Oczekująca"),
                    ("approved", "Zatwierdzona"),
                    ("cancelled", "Anulowana"),
                    ("rejected", "Odrzucona"),
                ],
                default="pending",
                max_length=12,
            ),
        ),
    ]
