# Generated by Django 5.2.8 on 2025-11-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_alter_reservation_slot"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="archived_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="archived_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
