# Generated by Django 5.2.8 on 2025-11-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_reservation_archived_end_reservation_archived_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="slot_duration",
            field=models.PositiveBigIntegerField(default=30),
        ),
    ]
