# Generated by Django 5.2.8 on 2025-11-27 14:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_service_slot_duration"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="timeslot",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="timeslot",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="booking.service"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="timeslot",
            unique_together={("service", "start", "end")},
        ),
    ]
